name: Kernel Build CI

on:
  push:
    branches:
      - sukisu
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Android Kernel Build Action
        id: kernel_builder
        uses: dabao1955/kernel_build_action@v1.9.0pre
        with:
          kernel-url: https://github.com/handingslider/android_kernel_6.1.git
          depth: 1 
          kernel-branch: sukisu
          config: gki_defconfig
          arch: arm64
          ccache: true
          aosp-clang: false
          aosp-clang-version: r522817
          aosp-gcc: true
          anykernel3: true
          anykernel3-url: https://github.com/handingslider/AnyKernel3.git
          other-clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86
      - name: Upload Flashable Zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}_${{ github.ref_name }}_Kernel_Zip
          path: ${{ steps.kernel_builder.outputs.zip_path }}
          retention-days: 7
